---
title: "Capstone Markdown"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

PLOT 1. neonic vs. total.prod (color = region)
```{r}
honey.csv <- read.csv("Honey_v03.csv")

neonicvtotalprod <- honey.csv %>%
  group_by(Region) 

ggplot(data = neonicvtotalprod, mapping = aes(x = nAllNeonic, y = totalprod, col = Region)) +
  geom_point() +
  labs (x = "Total Neonic (kg)", y = "Total Production (lb)", title = " Bee Honey Production under Neonic Pesticide by Region")
```


PLOT 2. neonic type vs. total prod (color = region)



```{r}
neonictype <- honey.csv %>%
  gather(key = c(nCLOTHIANIDIN, nIMIDACLOPRID, nTHIAMETHOXAM, nACETAMIPRID, nTHIACLOPRID), value = value) %>%
  print()

neonictype <- honey.csv %>%
  pivot_longer(cols = c(12,13,14,15,16), names_to = "neonictype", values_to = "x")


a <- ggplot(data = neonicvtotalprod, mapping = aes(x = nCLOTHIANIDIN, y = totalprod, col = Region)) + geom_point() + 
  labs(x = "Clothianidin (kg)", y = "Total Production (lb)")

b <- ggplot(data = neonicvtotalprod, mapping = aes(x = nIMIDACLOPRID, y = totalprod, col = Region)) + geom_point () +
  labs(x = "Imidacloprid (kg)", y = "Total Production (lb)")

c <-  ggplot(data = neonicvtotalprod, mapping = aes(x = nTHIAMETHOXAM, y = totalprod, col = Region)) + geom_point() +
  labs(x = "Thiamethoxam (kg)", y = "Total Production (lb)")

d <- ggplot(data = neonicvtotalprod, mapping = aes(x = nACETAMIPRID, y = totalprod, col = Region)) + geom_point() +
  labs(x = "Acetamiprid (kg)", y = "Total Production (lb)")

e <- ggplot(data = neonicvtotalprod, mapping = aes(x = nTHIACLOPRID, y = totalprod, col = Region)) + geom_point() +
  labs(x = "Thiacloprid (kg)", y = "Total Production (lb)")

library(cowplot)
library(ggpubr)
library(grid)

ggarrange(a, b, c, d, e + rremove("x.text"),
ncol = 2, nrow = 3) #+ grid_arrange() +
  #labs(x = "Neocin Type") #not a facetgrid pero similar na pero looking for ways na ma han ay sha like
# one label for y-axis
# only one area for the legend
# put general labels for title, x, and y - axis
```




